// Generated by CoffeeScript 1.6.2
(function() {
  var Transmission, child, exec, fetch_rssurl, parseString, rss_url, transmission;

  parseString = require('xml2js').parseString;

  Transmission = require('transmission');

  exec = require('child_process').exec;

  // 您在chd的rss地址
  rss_url = "http://chdbits.org/torrentrss.php?myrss=1&linktype=dl&uid=123445&passkey=abcd";

  // 填写您的transmission信息
  transmission = new Transmission({
    host: 'localhost',
    port: 9091,
    username: 'admin',
    password: '12345'
  });

  fetch_rssurl = "curl --silent '" + rss_url + "'";

  transmission.on('added', function(hash, id, name) {
    return console.log('成功添加了种子：', name);
  });

  console.log("开始读取rss..." + Date());

  child = exec(fetch_rssurl, function(error, stdout, stderr) {
    return parseString(stdout, function(err, result) {
      var item, items, torrent, _i, _len, _results;

      items = result.rss.channel[0].item;
      if (items) {
        console.log("找到了" + items.length + "个种子");
        _results = [];
        for (_i = 0, _len = items.length; _i < _len; _i++) {
          item = items[_i];
          torrent = item.enclosure[0].$.url;
          _results.push(transmission.add(torrent, function(err, result) {
            if (err) {
              return console.log(err);
            }
          }));
        }
        return _results;
      } else {
        return console.log("没有需要添加的种子.");
      }
    });
  });

}).call(this);
